sudo: false

matrix:
  fast_finish: true

language: php
  - 7.0
  - 7.1
before_script:
  - phpenv config-rm xdebug.ini || return 0
  - pecl instal swoole
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer run-script test


